
version: '3'

services:
  people-service-server:
    image: people-service-server:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    depends_on:
      - 'database'
    ports: 
      - '8080:8080'          

  database:
    image: mongo:latest